import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

export const sampleClinics = [
  {
    name: '서울대학교병원 피부과',
    address: '서울특별시 종로구 대학로 101',
    phone: '02-2072-2414',
    latitude: 37.5796,
    longitude: 127.0026,
    is_real_derma: true,
    has_insurance: true,
    specialties: ['아토피', '건선', '피부암', '두드러기'],
    review_count: 312,
    average_rating: 4.7,
    insurance_ratio: 0.92,
    real_derma_score: 0.95,
    data_source: 'manual',
  },
  {
    name: '연세대학교 세브란스병원 피부과',
    address: '서울특별시 서대문구 연세로 50-1',
    phone: '02-2228-2080',
    latitude: 37.5622,
    longitude: 126.9408,
    is_real_derma: true,
    has_insurance: true,
    specialties: ['아토피', '건선', '여드름', '피부종양'],
    review_count: 287,
    average_rating: 4.6,
    insurance_ratio: 0.89,
    real_derma_score: 0.93,
    data_source: 'manual',
  },
  {
    name: '강남세브란스병원 피부과',
    address: '서울특별시 강남구 언주로 211',
    phone: '02-2019-3360',
    latitude: 37.5218,
    longitude: 127.0473,
    is_real_derma: true,
    has_insurance: true,
    specialties: ['아토피', '건선', '피부염', '탈모'],
    review_count: 198,
    average_rating: 4.5,
    insurance_ratio: 0.85,
    real_derma_score: 0.91,
    data_source: 'manual',
  },
  {
    name: '서울아산병원 피부과',
    address: '서울특별시 송파구 올림픽로 43길 88',
    phone: '02-3010-3210',
    latitude: 37.5272,
    longitude: 127.1085,
    is_real_derma: true,
    has_insurance: true,
    specialties: ['피부암', '건선', '아토피', '두드러기'],
    review_count: 241,
    average_rating: 4.6,
    insurance_ratio: 0.88,
    real_derma_score: 0.94,
    data_source: 'manual',
  },
  {
    name: '고려대학교안암병원 피부과',
    address: '서울특별시 성북구 인촌로 73',
    phone: '02-920-5260',
    latitude: 37.5873,
    longitude: 127.0277,
    is_real_derma: true,
    has_insurance: true,
    specialties: ['여드름', '아토피', '건선', '피부염'],
    review_count: 156,
    average_rating: 4.4,
    insurance_ratio: 0.82,
    real_derma_score: 0.90,
    data_source: 'manual',
  },
  {
    name: '한양대학교병원 피부과',
    address: '서울특별시 성동구 왕십리로 222-1',
    phone: '02-2290-8280',
    latitude: 37.5571,
    longitude: 127.0434,
    is_real_derma: true,
    has_insurance: true,
    specialties: ['아토피', '건선', '피부염', '두드러기'],
    review_count: 134,
    average_rating: 4.3,
    insurance_ratio: 0.80,
    real_derma_score: 0.88,
    data_source: 'manual',
  },
  {
    name: '이화여자대학교목동병원 피부과',
    address: '서울특별시 양천구 안양천로 1071',
    phone: '02-2650-5164',
    latitude: 37.5274,
    longitude: 126.8754,
    is_real_derma: true,
    has_insurance: true,
    specialties: ['여드름', '아토피', '피부염', '탈모'],
    review_count: 112,
    average_rating: 4.3,
    insurance_ratio: 0.78,
    real_derma_score: 0.87,
    data_source: 'manual',
  },
  {
    name: '마포피부과의원',
    address: '서울특별시 마포구 마포대로 78',
    phone: '02-711-2323',
    latitude: 37.5444,
    longitude: 126.9512,
    is_real_derma: true,
    has_insurance: true,
    specialties: ['여드름', '아토피', '피부염'],
    review_count: 89,
    average_rating: 4.2,
    insurance_ratio: 0.75,
    real_derma_score: 0.82,
    data_source: 'crawl',
  },
  {
    name: '종로피부과',
    address: '서울특별시 종로구 종로 123',
    phone: '02-737-8800',
    latitude: 37.5705,
    longitude: 126.9820,
    is_real_derma: true,
    has_insurance: true,
    specialties: ['건선', '아토피', '두드러기'],
    review_count: 76,
    average_rating: 4.1,
    insurance_ratio: 0.72,
    real_derma_score: 0.80,
    data_source: 'crawl',
  },
  {
    name: '강남 루체체피부과',
    address: '서울특별시 강남구 강남대로 396',
    phone: '02-548-7588',
    latitude: 37.5048,
    longitude: 127.0245,
    is_real_derma: false,
    has_insurance: false,
    specialties: ['보톡스', '필러', '레이저'],
    review_count: 423,
    average_rating: 4.5,
    insurance_ratio: 0.02,
    real_derma_score: 0.12,
    data_source: 'crawl',
  },
  {
    name: '압구정 드림피부과',
    address: '서울특별시 강남구 압구정로 155',
    phone: '02-546-9191',
    latitude: 37.5270,
    longitude: 127.0340,
    is_real_derma: false,
    has_insurance: false,
    specialties: ['리프팅', '보톡스', '피부미용'],
    review_count: 567,
    average_rating: 4.6,
    insurance_ratio: 0.01,
    real_derma_score: 0.08,
    data_source: 'crawl',
  },
  {
    name: '홍대 스킨앤코 피부과',
    address: '서울특별시 마포구 양화로 141',
    phone: '02-333-5757',
    latitude: 37.5565,
    longitude: 126.9218,
    is_real_derma: false,
    has_insurance: false,
    specialties: ['레이저', '미백', '여드름치료'],
    review_count: 334,
    average_rating: 4.4,
    insurance_ratio: 0.05,
    real_derma_score: 0.18,
    data_source: 'crawl',
  },
  {
    name: '신촌연세피부과',
    address: '서울특별시 서대문구 신촌로 95',
    phone: '02-392-7788',
    latitude: 37.5558,
    longitude: 126.9368,
    is_real_derma: true,
    has_insurance: true,
    specialties: ['아토피', '건선', '여드름'],
    review_count: 98,
    average_rating: 4.2,
    insurance_ratio: 0.70,
    real_derma_score: 0.79,
    data_source: 'crawl',
  },
  {
    name: '강동성심병원 피부과',
    address: '서울특별시 강동구 성안로 150',
    phone: '02-2224-2230',
    latitude: 37.5486,
    longitude: 127.1460,
    is_real_derma: true,
    has_insurance: true,
    specialties: ['아토피', '피부염', '두드러기', '탈모'],
    review_count: 121,
    average_rating: 4.3,
    insurance_ratio: 0.81,
    real_derma_score: 0.86,
    data_source: 'manual',
  },
  {
    name: '강남 뷰티스킨피부과',
    address: '서울특별시 강남구 테헤란로 152',
    phone: '02-557-3399',
    latitude: 37.5001,
    longitude: 127.0375,
    is_real_derma: false,
    has_insurance: false,
    specialties: ['보톡스', '필러', '리프팅', '레이저토닝'],
    review_count: 612,
    average_rating: 4.7,
    insurance_ratio: 0.00,
    real_derma_score: 0.05,
    data_source: 'crawl',
  },
];

export async function seedDatabase() {
  const supabase = createClient(supabaseUrl, supabaseKey);

  console.log(`Seeding ${sampleClinics.length} clinics...`);

  for (const clinic of sampleClinics) {
    const { latitude, longitude, ...rest } = clinic;

    const { error } = await supabase.from('clinics').insert({
      ...rest,
      latitude,
      longitude,
      location: `POINT(${longitude} ${latitude})`,
    });

    if (error) {
      console.error(`Failed to insert "${clinic.name}":`, error.message);
    } else {
      console.log(`Inserted: ${clinic.name}`);
    }
  }

  console.log('Seeding complete.');
}

// Run directly: npx ts-node scripts/seed-data.ts
if (require.main === module) {
  seedDatabase().catch(console.error);
}
